### ISSUE TITLE
Suffocation when traveling

### ISSUE THREAD

**Issue by prozacgod** [tickleman/RealTeleporter#2]
Hey, I used to use this plugin .. A LOT .. - had 100's of "pads" everywhere... I started up a new server and when I created a test spot it can travel to the "home" position with no issue, but traveling to the destination it shoots me 10 blocks into the ground and I suffocate, any ideas ?

Debugging:
at first I thought, it might have been some floating point rounding issue, so I carefully sat in the middle of the block, and created the tp.

then I tried creating the point removing 5 layers of ground in a 3x3 centered on the point, and it worked,  I added floor until the floor was 2 layers thick (TP point inclusive) anything after this is where I would start to get stuck in the ground.

**Comment by prozacgod** [comment]
Haha this was old, I'm Closing/abandoning thread to clean up my list of open issues ;)

Regards.

**Comment by tickleman** [comment]
Yes, so old. Sorry I did not see this on time !
